spring:
  application:
    name: garage-service
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    serialization:
      write-dates-as-timestamps: false

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/garage}
    username: ${SPRING_DATASOURCE_USERNAME:garage}
    password: ${SPRING_DATASOURCE_PASSWORD:garage}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 3003

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html

app:
  simulator-base-url: ${APP_SIMULATOR_BASE_URL:http://simulator:3000}

logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: DEBUG
